name: Demo Workflow
on: 
  push: 
    branches: 
      - main
      
  workflow_dispatch:

jobs: 
  simple-etl:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python 
        uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
          cache: "pip"
      - name: install libraries
        run: pip install -r requirements.txt
      - name: run python file as testing
        run: python covid_19_data.py

      - name: print weather api key
        run: echo ${{ secrets.WEATHER_KEY }}

      - name: Run ETL pipeline
        run : python etl_demo.py
        env: 
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          SQLITE_DB: ${{ secrets.SQLITE }}
          