name: Demo Workflow
on: 
  push: 
    branches: 
      - main
      - apache_airflow
      
  workflow_dispatch:

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World
        run: echo "Hello World"
